# This is a manually triggered workflow (hence on: workflow_dispatch).
# See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#manual-events

# We can use this tool to run actions locally using local docker daemon
# https://github.com/nektos/act

# Related task https://github.com/ably/ably-js/issues/805

# To start this workflow using `act`:
# act -v -j publish -e .github/example-publish-event.json

on:
  workflow_dispatch:
    inputs:
      changesetType:
        description: 'can be `major`,`minor` or `patch`, used to bump version'
        required: true

jobs:
  publish:
    # todo - act uses ubuntu-18.04 image, not `ubuntu-latest`, is it ok?
    # i cannot say i'm fan of ubuntu, i prefer centos --Anatolij
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        name: 'setup node'
        with:
          node-version: '14.x'

      - name: 'install'
        run: npm ci

# we load release type (major/minor/patch) from event inputs
# TODO - need to set github actions secrets as described here
# https://docs.github.com/en/actions/security-guides/encrypted-secrets
      - name: 'prepare release github release, aka bump version, make tag, etc'
        env:
          GITHUB_USERNAME: "${{ secrets.GITHUB_USERNAME }}"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: "npm run-script publish-release ${{ github.event.inputs.changesetType }}"

# Seems like its not so trivial to set npmjs authorization https://github.com/npm/npm/issues/15565
# See also https://github.com/workshopper/how-to-npm/issues/25
# TODO - need to set github actions secrets as described here
# https://docs.github.com/en/actions/security-guides/encrypted-secrets

      - name: setup npmjs credentials
        run: "npm config set _auth ${{ secrets.NPMJS_AUTH_SECRET }}"

      - name: setup npmjs registry
        run: npm config set registry "https://registry.npmjs.org/"

      - name: setup authorization enabled
        run: npm config set always-auth=true

      - name: setup authorization enabled
        run: npm config set email support@ably.com # todo confirm

# when we have set authorization, we can try to `npm publish` this package to npmjs.org registry
      - name: publish npm package
#        run: npm publish
        run: "true"

# TODO: upload artifacts to CDN
# command to be executed - https://github.com/ably/ably-js/blob/b5d0015bafda91585bddecff282531d0f1df40cb/Gruntfile.js#L339
      - name: upload artifacts to CDN
        # run: npm run-script release:ably-deploy
        run: "true"
